data(mtcars)
head(mtcars)
getwd()
library(dplyr)
library(tidyverse)
install.packages("tidyverse")
getwd()
library(tidyverse)
library(tidyverse)
install.packages("dplyr")
library(dplyr)
packageVersion(swirl)
install.packages("swirl")
packageVersion("swirl")
library(swirl)
install_from_swirl("R Programming")
swirl()
TRUE==TRUE
FALSE==TRUE
(FALSE==TRUE)==FALSE
6==7
6<7
10<=10
5!=7
5==7
!(5==7)
FALSE & FALSE
TRUE & c(TRUE, FALSE, FALSE)
TRUE && c(TRUE, FALSE, FALSE)
TRUE | c(TRUE, FALSE, FALSE)
TRUE || c(TRUE, FALSE, FALSE)
 5 > 8 || 6 != 8 && 4 > 3.9
isTRUE(6>4)
identical('twins', 'twins')
xor(5
| == 6, !FALSE)
xor(5==6,!FALSE)
ints<-sample(10)
ints
ints>5
which(ints>7)
any(ints<0)
all(ints>0)
Sys.Date()
mean(c(2,4,5))
submit()
 boring_function('My first function!')
boring_function
submit()
my_mean(c(4,5,10))
submit()
submit()
submit()
remainder(5)
remainder(11,5)
remainder(divisor = 11, num =5)
r(4, div = 2)
remainder(4, div = 2)
args(remainder)
submit()
getwd()
sd(c(1.4, 3.6, 7.9, 8.8))
evaluate(sd,c(1.4, 3.6, 7.9, 8.8))
evaluate(function(x){x+1}, 6)
getwd()
evaluate(function(x){x[0]},c(8,4,0))
evaluate(function(x){x[0]}, dat=c(8,4,0))
evaluate(function(x){x[0]},c(8,4,0))
evaluate(function(x){x[0]}, dat=c(8,4,0)
}
evaluate(function(x){x[1]}, c(8, 4, 0))
evaluate(function(x){x[length(x)]}, c(8, 4, 0))
?paste
 paste("Programming", "is", "fun!")
submit()
telegram(i , am, the, bext)
telegram("I","am","the","best")
submit()
mad_libs(place = "London", adjustive = "beautiful", noun = "dog")
submit()
submit()
"I" %p% "love" %p% "R!"
q()
x<- rnorm(100,2,4)
summary(x)
x<-rnorm(20
)
x
y<-rnorm(100,0,2)
yy<-0.5+2*x+y
yy
plot(x,y)
x<-rnorm(100)
plot(x,yy)
set.seed(1)
rpois(5, 2)
install.packages("swirl")
packageVersion("swirl")
library(swirl)
install_from_swirl("R Programming")
swirl()
ls()
class(plants)
dim(plants)
nrow(plants)
ncol(plants)
object.size(plants)
names(plants)
head(plants)
head(plants,10)
taile(plants,15)
tail(plants,15)
summary(plants)
 table(plants$Active_Growth_Period)
str(plants)
?sample
sample(1:6,4,replace=TRUE)
sample(1:6,4,replace=TRUE)
sample(1:20,10)
LETTERS
sample(LETTERS)
getwd()
flips <- sample(c(0,1), 100, replace = TRUE, prob = c(0.3, 0.7))
flips
sum(flips)
?rbinom
getwd()
rbinom(1,100,0.7)
flips2<-rbinom(1,100,0.7)
flips2<-rbinom(100,1,0.7)
flips2
sum(flips2)
?rnorm
rnorm(10)
getwd()
rnorm(10,100,25)
?rpois
rpois()
rpois(5,10)
my_pois<-replicate(100, rpois(5, 10))
my_pois
cm<-colMeans(my_pois)
hist(cm)
data(cars)
?cars
head(cars)
plot(cars)
?plot
plot(x,y)
plot(x = cars$speed, y = cars$dist)
plot(x = cars$dist, y = cars$speed)
plot(x = cars$speed, y = cars$dist)
plot(x = cars$speed, y = cars$dist, xlab="Speed")
plot(x = cars$speed, y = cars$dist, xlab="Speed",ylab="Stopping Distance")
(x = cars$speed, y = cars$dist, ylab = "Stopping Distance")
(x = cars$speed, y = cars$dist, ylab = "Stopping Distance")
plot(x = cars$speed, y = cars$dist, ylab = "Stopping Distance")
plot(x = cars$speed, y = cars$dist, xlab="Speed",ylab = "Stopping Distance")
plot(x = cars$speed, y = cars$dist, xlab="Speed",ylab = "Stopping Distance")
plot(cars,main="My plot")
plot(cars, main = "My Plot")
plot(cars, main = "My Plot")
plot(cars, sub = "My Plot Subtitle")
plot(cars, sub = "My Plot Subtitle")
 plot(cars, col = 2) 
 plot(cars, col = 2) 
 plot(cars, xlim = c(10, 15))
plot(cars,pch=2)
plot(cars,pch=2)
data(mtcars)
?boxplot
?boxplot
getwd()
 boxplot(formula = mpg ~ cyl, data = mtcars)
hist(mtcars$mpg)
